### ISSUE TITLE
Advanced View Pager won't run with Xamarin Shell

### ISSUE THREAD

**Issue by DamienDoumer** [PDFTron/xamarin-forms-sample#14]
The advanced viewpager sample won't run on the Xamarin.Forms Shell. 

# Expected Behavior
Let the advanced pdfview run without any issue inside a Xamarin Forms app that leverages the Shell architecture.

# Reproduction: 
I reproduced this bug in [a repository of mine on github](https://github.com/DamienDoumer/BugRepro).
Just run the sample, and press on the button on the screen to start the viewpager sample and the app will crash.

If you replace the main page with a shell, and nest the main page inside this shell, wuthout changing the code behind, and launch the viewpager, the sample app crashes with the following error: 

`
[AndroidRuntime] Caused by: java.lang.reflect.InvocationTargetException
[AndroidRuntime] 	at java.lang.reflect.Constructor.newInstance0(Native Method)
[AndroidRuntime] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
[AndroidRuntime] 	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
[AndroidRuntime] 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
[AndroidRuntime] 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
[AndroidRuntime] 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
[AndroidRuntime] 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
[AndroidRuntime] 	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
[AndroidRuntime] 	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
[AndroidRuntime] 	at android.view.ViewStub.inflateViewNoAdd(ViewStub.java:272)
[AndroidRuntime] 	at com.pdftron.pdf.controls.PdfViewCtrlTabBaseFragment.loadStubPDFViewCtrl(PdfViewCtrlTabBaseFragment.java:3526)
[AndroidRuntime] 	at com.pdftron.pdf.controls.PdfViewCtrlTabBaseFragment.loadPDFViewCtrlView(PdfViewCtrlTabBaseFragment.java:3537)
[AndroidRuntime] 	at com.pdftron.pdf.controls.PdfViewCtrlTabFragment2.loadPDFViewCtrlView(PdfViewCtrlTabFragment2.java:233)
[AndroidRuntime] 	at androidx.fragment.app.FragmentStateManager.moveToExpec03-24 22:45:22.263 E/AndroidRuntime(19159): 	at com.pdftron.pdf.controls.PdfViewCtrlTabBaseFragment.onViewCreated(PdfViewCtrlTabBaseFragment.java:1210)
[AndroidRuntime] 	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
[AndroidRuntime] 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
[AndroidRuntime] 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
[AndroidRuntime] 	at androidx.fragment.app.FragmentStateMan03-24 22:45:22.263 E/AndroidRuntime(19159): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3138)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:3065)
[AndroidRuntime] 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
[AndroidRuntime] 	tedState(FragmentStateManager.java:282)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1971)
[AndroidRuntime] 	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:305)
[AndroidRuntime] 	at com.pdftron.pdf.controls.DocumentView2.prepView(DocumentView2.java:124)
[AndroidRuntime] 	at com.pdftron.pdf.controls.DocumentView2.onAttachedToWindow(DocumentView2.java:152)
[AndroidRuntime] 	at android.view.View.dispatchAttachedToWindow(View.java:20887)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3523)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3530)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3530)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3530)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3530)
[AndroidRuntime] 	at android.view.ViewGroup.addViewInner(ViewGroup.java:5362)
[AndroidRuntime] 	at android.view.ViewGroup.addView(ViewGroup.java:5140)
[AndroidRuntime] 	at android.view.ViewGroup.addView(ViewGroup.java:5080)
[AndroidRuntime] 	at androidx.fragment.app.FragmentStateManager.addViewToContainer(FragmentStateManager.java:833)
[AndroidRuntime] 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:523)
[AndroidRuntime] 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
[AndroidRuntime] 	at android.os.Handler.handleCallback(Handler.java:938)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[AndroidRuntime] 	at android.os.Looper.loopOnce(Looper.java:233)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:344)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:8184)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
[AndroidRuntime] Caused by: java.lang.UnsatisfiedLinkError: No implementation found for long com.pdftron.pdf.Rect.RectCreate(double, double, double, double) (tried Java_com_pdftron_pdf_Rect_RectCreate and Java_com_pdftron_pdf_Rect_RectCreate__DDDD)
[AndroidRuntime] 	at com.pdftron.pdf.Rect.RectCreate(Native Method)
[AndroidRuntime] 	at com.pdftron.pdf.Rect.<init>(SourceFile:30)
[AndroidRuntime] 	at com.pdftron.pdf.PDFViewCtrl$u.<init>(SourceFile:11000)
[AndroidRuntime] 	at com.pdftron.pdf.PDFViewCtrl.<init>(SourceFile:15868)
[AndroidRuntime] 	at com.pdftron.pdf.PDFViewCtrl.<init>(SourceFile:1943)
[AndroidRuntime] 	... 56 more
**Android.Views.InflateException:** 'Loading...
`

**Comment by sgong-pdftron** [comment]
Please submit support request through https://www.pdftron.com/support/. Thanks.
